#if !defined(STDAFX_H__7F7767C7_365B_11D0_9C9D_00A0D100E3C8__INCLUDED_)
#define STDAFX_H__7F7767C7_365B_11D0_9C9D_00A0D100E3C8__INCLUDED_

// stdafx.h : include file for standard system include files,
//      or project specific include files that are used frequently,
//      but are changed infrequently

#define VC_EXTRALEAN		// Exclude rarely-used stuff from Windows headers

#include <afxctl.h>         // MFC support for ActiveX Controls

// Delete the two includes below if you do not wish to use the MFC
//  database classes
#include <afxdb.h>			// MFC database classes
#include <afxdao.h>			// MFC DAO database classes

//{{AFX_INSERT_LOCATION}}
// Microsoft Developer Studio will insert additional declarations immediately before the previous line.

#endif // !defined(STDAFX_H__7F7767C7_365B_11D0_9C9D_00A0D100E3C8__INCLUDED_)
