//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by UseClock.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_USECLOCK_FORM               101
#define IDR_MAINFRAME                   128
#define IDR_USECLOTYPE                  129
#define IDD_HOURS_MINUTES               131
#define IDD_CLOCK_PROPERTIES            132
#define IDC_CLOCKCTRL                   1000
#define IDC_HOURS                       1001
#define IDC_MINUTES                     1002
#define IDC_TYPE                        1005
#define IDC_COMMAND                     1006
#define ID_CLOCK_TOGGLEALARM            32773
#define ID_CLOCK_SETALARMHOUR           32774
#define ID_CLOCK_SETALARMMINUTE         32775
#define ID_CLOCK_SETBACKCOLOR           32776
#define ID_CLOCK_ALARMTIMEMETHOD        32777
#define ID_CLOCK_TESTALARMMETHOD        32778
#define ID_CLOCK_ABOUTBOXMETHOD         32779
#define ID_CLOCK_SETALARMCOMMAND        32780
#define ID_CLOCK_SHOWPROPERTIES         32781

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32782
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
