//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by PalView.rc
//
#define IDS_PALVIEW                     1
#define IDD_ABOUTBOX_PALVIEW            1
#define IDB_PALVIEW                     1
#define IDI_ABOUTDLL                    1
#define IDS_PALVIEW_PPG                 2
#define IDD_PROPPAGE_DIBFILE            104
#define IDS_PALVIEW_PPG_CAPTION         200
#define IDD_PROPPAGE_PALVIEW            200
#define IDC_COLORSELECTION              201
#define IDS_DIBPAGE                     201
#define IDC_3D_BOXES                    202
#define IDS_DIBPAGE_CAPTION             202
#define IDC_DIB_FILENAME                203
#define IDC_BROWSE                      204

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        202
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         205
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
