//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by OwnDraw.rc
//
#define COLOR_BOX_HEIGHT                20
#define COLOR_BOX_WIDTH                 30
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_OWNERDTYPE                  129
#define IDB_BLACK                       130
#define IDB_RED                         131
#define IDB_GREEN                       132
#define IDB_BLUE                        133
#define IDR_COLOR_FIRST                 0x7000
#define IDR_COLOR_BLACK                 0x7000
#define IDR_COLOR_BLUE                  0x7001
#define IDR_COLOR_GREEN                 0x7002
#define IDR_COLOR_CYAN                  0x7003
#define IDR_COLOR_RED                   0x7004
#define IDR_COLOR_LAST                  0x7004
#define IDS_WELCOME_MSG                 57605

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        134
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           115
#endif
#endif
