//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by List.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_LISTTYPE                    129
#define ID_BLACK                        61204
#define ID_BLUE                         61205
#define ID_GREEN                        61206
#define ID_CYAN                         61207
#define ID_RED                          61208
#define ID_PURPLE                       61209
#define ID_YELLOW                       61210
#define ID_WHITE                        61211
#define ID_COLUMN1                      61212
#define ID_COLUMN2                      61213
#define ID_COLUMN3                      61214
#define ID_COLUMN4                      61215

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
