//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Toolbar.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_ADDITITYPE                  129
#define IDR_COLOR_TOOLBAR               130
#define ID_COLORS_BLACK                 32771
#define ID_COLORS_RED                   32772
#define ID_COLORS_GREEN                 32773
#define ID_COLORS_BLUE                  32774
#define ID_VIEW_COLORTOOLBAR            32775
#define IDS_COLORTB_CREATE              61204
#define IDS_COLORTB_LOAD                61205
#define IDS_WELCOME_MSG                 61206

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
