//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TmpGraph.rc
//
#define DEFAULT_TEMPERATURE             10
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_TEMPERTYPE                  129
#define IDD_TEMPERATURE                 130
#define IDC_DAY_SPINNER                 1000
#define IDC_TEMP_SPINNER                1001
#define IDC_DAY                         1002
#define IDC_TEMPERATURE                 1003
#define IDC_APPLY                       1004
#define ID_CHANGE_SETDAILYTEMP          32771
#define ID_MONTH_JANUARY                32772
#define ID_MONTH_FEBRUARY               32773
#define ID_MONTH_MARCH                  32774
#define ID_MONTH_APRIL                  32775
#define ID_MONTH_MAY                    32776
#define ID_MONTH_JUNE                   32777
#define ID_MONTH_JULY                   32778
#define ID_MONTH_AUGUST                 32779
#define ID_MONTH_SEPTEMBER              32780
#define ID_MONTH_OCTOBER                32781
#define ID_MONTH_NOVEMBER               32782
#define ID_MONTH_DECEMBER               32783
#define ID_MONTH_LEAPFEBRUARY           32784
#define IDS_JANUARY                     37000
#define IDS_FEBRUARY                    37001
#define IDS_MARCH                       37002
#define IDS_APRIL                       37003
#define IDS_MAY                         37004
#define IDS_JUNE                        37005
#define IDS_JULY                        37006
#define IDS_AUGUST                      37007
#define IDS_SEPTEMBER                   37008
#define IDS_OCTOBER                     37009
#define IDS_NOVEMBER                    37010
#define IDS_DECEMBER                    37011
#define IDS_LEAP_FEBRUARY               37012

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32785
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
