//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Tabbed.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_TABBEDTYPE                  129
#define IDD_PHRASE                      130
#define IDD_COLORS                      131
#define IDC_PHRASE                      1000
#define IDC_BLACK                       1001
#define IDC_RED                         1002
#define IDC_GREEN                       1003
#define IDC_BLUE                        1004
#define IDC_COLOR_LIST                  1005
#define ID_MODIFY_SHOWTABBEDDIALOGBOX   32771
#define IDS_WELCOME_MSG                 57638

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
