//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Clock.rc
//
#define IDS_CLOCK                       1
#define IDD_ABOUTBOX_CLOCK              1
#define IDB_CLOCK                       1
#define IDI_ABOUTDLL                    1
#define IDS_CLOCK_PPG                   2
#define IDD_ABOUTBOX_TIME               2
#define IDB_TIME                        2
#define IDS_TIME                        3
#define IDS_ALARM_PPG                   3
#define IDS_TIME_PPG                    4
#define IDS_CLOCK_PPG_CAPTION           100
#define IDD_PROPPAGE_CLOCK              100
#define IDS_TIME_PPG_CAPTION            101
#define IDD_PROPPAGE_TIME               101
#define IDS_ALARM_PPG_CAPTION           101
#define IDD_PROPPAGE_ALARM              102
#define IDC_ALARM_HOUR                  202
#define IDC_ALARM_MINUTE                203
#define IDC_ALARM_SOUND                 204
#define IDC_ALARM_SET                   205
#define IDC_ALARM_SET_ON                206
#define IDC_FILE_SELECT                 207
#define IDC_ALARM_COMMAND               208
#define IDC_ALARM_TYPE                  211
#define IDS_ALARMTYPE_EVENT             1000
#define IDS_ALARMTYPE_SOUND             1001
#define IDS_ALARMTYPE_COMMAND           1002
#define IDS_ALARMTYPE_ALL               1003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         32768
#define _APS_NEXT_CONTROL_VALUE         212
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
