//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Print.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_PrintTYPE                  129
#define IDD_PRINTLINES_DIALOG           130
#define IDR_DUMMY                       131
#define IDC_SPIN                        1000
#define IDC_LINES                       1001
#define ID_FILE_LINESPERPAGE            32772
#define ID_DUMMY_PAGELENGTH             32773
#define IDS_COMPANY_LOGO                57610
#define IDS_PAGE                        57611
#define IDS_WELCOME_MSG                 61446

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
