//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by CustSBar.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_CUSTOMTYPE                  129
#define IDM_REDBITMAP                   130
#define IDM_BLACKBITMAP                 131
#define IDM_GREENBITMAP                 132
#define IDM_BLUEBITMAP                  133
#define IDR_DUMMY                       134
#define ID_COLORS_BLACK                 32771
#define ID_COLORS_RED                   32772
#define ID_COLORS_GREEN                 32773
#define ID_COLORS_BLUE                  32774
#define ID_COLORS_COLORS                32775
#define ID_KEYBOARD_INS                 32777
#define IN_INDICATOR_CAPX               32778
#define IDS_WELCOME_MSG                 61204

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
