//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by diff.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_DIFFTYPE                    129
#define IDD_OPENFILES                   130
#define IDD_NEXTDIFF                    132
#define IDC_EDIT_FILE1                  1000
#define IDC_EDIT_FILE2                  1001
#define IDC_BUTTON_FILE1_BROWSE         1002
#define IDC_BUTTON_FILE2_BROWSE         1003
#define IDC_RADIO_NEXTDIFF              1008
#define IDC_RADIO_NEXTEQUAL             1009
#define IDC_RADIO_UP                    1010
#define IDC_RADIO_DOWN                  1011
#define IDC_EDIT_COLOR_ADDITIONS        32771
#define IDC_EDIT_COLOR_DELETIONS        32772
#define ID_EDIT_FONT                    32773
#define IDS_ERRFMT_INVALIDFILE          61446
#define IDS_COMPARING                   61447

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        133
#define _APS_NEXT_COMMAND_VALUE         32774
#define _APS_NEXT_CONTROL_VALUE         1011
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
