//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Modeless.rc
//
#define IDD_ABOUTBOX                    100
#define IDD_PHRASE_MODELESS             102
#define IDR_MAINFRAME                   128
#define IDR_MODELETYPE                  129
#define IDC_PHRASE                      1000
#define IDC_APPLY                       1001
#define IDC_COLOR_LIST                  1003
#define ID_MODIFY_DISPLAYMODELESSDIALOG 32771
#define IDS_WELCOME_MSG                 57638

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32772
#define _APS_NEXT_CONTROL_VALUE         1002
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
