//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by DlgBars.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_DLGBARTYPE                  129
#define IDD_DIALOG_BAR                  130
#define IDI_BLUE                        134
#define IDI_RED                         135
#define IDC_LIST_COLORS                 1002
#define ID_COLORS_BLACK                 32771
#define ID_COLORS_RED                   32772
#define ID_COLORS_GREEN                 32773
#define ID_COLORS_BLUE                  32774
#define IDS_WELCOME_MSG                 57638
#define ID_VIEW_MYDIALOGBAR             59425
#define ID_VIEW_DIALOGBAR               0xE821

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1003
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
