//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by splitter.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_SPLITTTYPE                  129
#define ID_COLORS_BLACK                 32771
#define ID_COLORS_RED                   32772
#define ID_COLORS_GREEN                 32773
#define ID_COLORS_BLUE                  32774
#define IDS_WELCOME_MSG                 61204

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        130
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
