//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by TreeWithImages.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_TREEWITYPE                  129

#define NUM_BITMAPS                     10
#define BITMAP_HEIGHT                   15
#define BITMAP_WIDTH                    16

#define AMPHIBIAN  0
#define BIRD       2
#define FISH       4
#define MAMMAL     6
#define REPTILE    8

#define IDB_AMPHIBIAN                   130
#define IDB_AMPHIBIAN_SELECTED          131

#define IDB_BIRD                        132
#define IDB_BIRD_SELECTED               133

#define IDB_FISH                        134
#define IDB_FISH_SELECTED               135

#define IDB_MAMMAL                      136
#define IDB_MAMMAL_SELECTED             137

#define IDB_REPTILE                     138
#define IDB_REPTILE_SELECTED            139

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
