//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by tree.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_TREETYPE                    129
#define IDD_ANIMAL_ENTRY                140
#define IDD_ANIMAL_MODIFY               141
#define IDD_TYPE_MODIFY                 142
#define IDC_CLASS_LIST                  1000
#define IDC_TYPE                        1001
#define IDC_ANIMAL                      1002
#define IDC_WEIGHT                      1003
#define ID_EDIT_MODIFYANIMAL            32772
#define ID_EDIT_DELETEANIMAL            32773
#define ID_EDIT_ADDANIMAL               32774
#define IDS_AMPHIBIANS                  57605
#define IDS_BIRDS                       57606
#define IDS_FISHES                      57607
#define IDS_MAMMALS                     57608
#define IDS_REPTILES                    57609

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        143
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1004
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
