//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by IC_2.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_IC_2TYPE                    129
#define IDD_URL_DIALOG                  130
#define IDC_EDIT_URL                    1000
#define IDC_PARSE                       1001
#define IDC_SERVER                      1002
#define IDC_OBJECT                      1003
#define IDC_PORT                        1004
#define IDC_SERVICE_TYPE                1005
#define ID_INTERNET_CREATESESSION       32771
#define ID_INTERNET_GETCONNECTION       32772
#define ID_INTERNET_OPENREQUEST         32773
#define ID_INTERNET_SENDREQUEST         32774
#define ID_INTERNET_READINFORMATION     32775
#define ID_INTERNET_CLOSESESSION        32776
#define ID_INTERNET_OBTAINURL           32777
#define ID_INTERNET_ALLTHEABOVE         32778

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32779
#define _APS_NEXT_CONTROL_VALUE         1006
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
